var data = {
    "seriests": null,
    "pageInfo": {
        "pageNum": 6,
        "pageSize": 16,
        "size": 16,
        "startRow": 81,
        "endRow": 96,
        "total": 129,
        "pages": 9,
        "list": [
            {
                "fupin": 1,
                "search": null,
                "fullname": null,
                "publi": 1,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 244,
                "publishTime": null,
                "title": "小学六年级单词精讲unit4",
                "picURL": "hukiuyiyiyierersisi.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 9869,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 80,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 1,
                "search": null,
                "fullname": null,
                "publi": 1,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 245,
                "publishTime": null,
                "title": "小学六年级 语法精讲unit1",
                "picURL": "huliankuyiyiy.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 25712,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 67,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 246,
                "publishTime": null,
                "title": "小学六年级 unit2",
                "picURL": "huliukuier.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 9855,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 89,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 247,
                "publishTime": null,
                "title": "小学六年级 unit3",
                "picURL": "huliukuiersnsansan.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 96588,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 670,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 248,
                "publishTime": null,
                "title": "小学六年级英语unit4",
                "picURL": "huliukuiersnsisi.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 65335,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 410,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 1,
                "search": null,
                "fullname": null,
                "publi": 1,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 249,
                "publishTime": null,
                "title": "小学六年级unit1",
                "picURL": "20171023183352.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 98577,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 432,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 250,
                "publishTime": null,
                "title": "小学六年级 unit2",
                "picURL": "20171023183339.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 56992,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 530,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 251,
                "publishTime": null,
                "title": "小学六年级 unit3",
                "picURL": "20171023183328.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 32661,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 990,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 252,
                "publishTime": null,
                "title": "小学六年级课文精讲unit4",
                "picURL": "20171023183315.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 65988,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 30,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "222"
            },
            {
                "fupin": 1,
                "search": null,
                "fullname": null,
                "publi": 1,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 253,
                "publishTime": null,
                "title": "六年级一单元 分数除法",
                "picURL": "yuyuyiyiyi.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 69829,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 0,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 94,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "221"
            },
            {
                "fupin": 1,
                "search": null,
                "fullname": null,
                "publi": 1,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 254,
                "publishTime": null,
                "title": "六年级二单元 位置与方向",
                "picURL": "yuyuyiyiyierer.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 98542,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 0,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 328,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "221"
            },
            {
                "fupin": 1,
                "search": null,
                "fullname": null,
                "publi": 1,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 255,
                "publishTime": null,
                "title": "六年级三单元—分数除法",
                "picURL": "yuyuyiyiyierersansan.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 65251,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 0,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 430,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "221"
            },
            {
                "fupin": 1,
                "search": null,
                "fullname": null,
                "publi": 1,
                "syn": "sy",
                "free": null,
                "typeName": null,
                "id": 256,
                "publishTime": null,
                "title": "六年级四单元——比",
                "picURL": "yuyuyiyiyierersisi.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 48571,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 0,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 320,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "221"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "ff",
                "free": null,
                "typeName": null,
                "id": 257,
                "publishTime": null,
                "title": "小升初应用题专题",
                "picURL": "xiaoshengchu.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 79854,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 197,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "221"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "ff",
                "free": null,
                "typeName": null,
                "id": 258,
                "publishTime": null,
                "title": "什么样的立意让文章脱颖而出",
                "picURL": "zuowenliyi.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 98587,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 870,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "219",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": "220"
            },
            {
                "fupin": 0,
                "search": null,
                "fullname": null,
                "publi": 0,
                "syn": "hobby",
                "free": null,
                "typeName": null,
                "id": 259,
                "publishTime": null,
                "title": "5分钟学绘画 so easy",
                "picURL": "huihuaxiao.jpg",
                "createTime": null,
                "price": 0,
                "clickRate": 98848,
                "pmtsTot": 0,
                "isPrice": 0,
                "realPrice": 49,
                "teacherID": 0,
                "isValid": 0,
                "thuPicURL": null,
                "collection": 901,
                "timeLimit": 0,
                "picURL2": null,
                "isDiscount": 0,
                "type2Value": "297",
                "videoCount": 0,
                "remark": "",
                "typeValue": "189",
                "type3Value": null
            }
        ],
        "prePage": 5,
        "nextPage": 7,
        "isFirstPage": false,
        "isLastPage": false,
        "hasPreviousPage": true,
        "hasNextPage": true,
        "navigatePages": 8,
        "navigatepageNums": [
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9
        ],
        "navigateFirstPage": 2,
        "navigateLastPage": 9,
        "firstPage": 2,
        "lastPage": 9
    }
}

//初始化默认显示当前为第一页
pageAjax('1');
//点击分页效果
$('#pagefenye').on('click','.list',function(){
	if($(this).hasClass('pageItemDisable')) {
		return false;
	}else if($(this).hasClass('pageItemactive')){
		return false;
	}else{
		var $id = $(this).attr('data-page');
		//console.log($id);
		pageAjax($id);
	}
});
//ajax 封装
function pageAjax(id){
	$.ajax({
	type:"get",
	url:"http://192.168.8.37:8080/STK/selorderandk?startpage="+id,
	async:true,
	dataType: 'jsonp',
	jsonp: "callback",//一般默认为:callback
    jsonpCallback:"success_jsonpCallback",//自定义的jsonp回调函数名称，默认为jQuery自动生成的随机函数名，也可以写"?"，jQuery会自动为你处理数据
    success: function(data){
        /**
         * 获得服务器返回的信息。
         * 可以做具体的业务处理。
         */
        //alert('标题：ID： ' + json.title + ' ，背景： ' + json.bg + '。');
        console.log(data);
        //生成分页
        pageCreate(data.pageInfo,$('#pagefenye'));
        //生成课程模块
        var kcArry = data.pageInfo.list;
        createLi(kcArry,$('#zhkc'));
    },
    error: function(){
        alert('服务器离家出走了。。。。。');
    }
});
}

//根据数据生成分页 name是放分页的容器
function pageCreate(data,name){
	name.empty();
	var strfirst = '<li class="list '+(data.isFirstPage?'pageItemDisable':'pageItem')+'" data-page="1">首页</li>';
	var strprev = '<li class="list '+(data.isFirstPage?'pageItemDisable':'pageItem')+'"  data-page="'+data.prePage+'">上一页</li>';
    name.append(strfirst);
    name.append(strprev);
	var strnext = '<li class="list '+(data.isLastPage?'pageItemDisable':'pageItem')+'"  data-page="'+data.nextPage+'">下一页</li>';
	var strlast = '<li class="list '+(data.isLastPage?'pageItemDisable':'pageItem')+'"  data-page="'+data.pages+'">尾页</li>';
	var arry = data.navigatepageNums;
	$.each(arry,function(i,val){
		var items = '<li class="list '+(data.pageNum==arry[i]?'pageItemactive':'pageItem')+'" data-page="'+arry[i]+'">'+arry[i]+'</li>';
		name.append(items);
	});
	name.append(strnext);
	name.append(strlast);
	
}

//根据数据和分页生成课程模块 name是放课程模块的容器
function createLi(arry,name){
	name.empty();
	$.each(arry,function(i,val){
		$('<li><a href="javascript:;"><div class="kc"><div class="kctop"><img class="lazy" alt="" width="200" height="124" data-original="img/example.jpg" src="http://www.shoutike.com/STK/cover/'+arry[i].seriesid.picURL+'" /></div><div class="kcmask"></div></div><div class="texts"><div class="titles">西医综合导学</div><div class="kcsm"><div class="kcsm-top"><p><span></span><span>43543</span></p><p><em>￥19.99</em></p></div><div class="kcsm-foot"><p>'+arry[i].seriesid.title+'</p></div></div></div></a></li>').appendTo(name);
	});
}
